
server:
  port: 6666

spring:
  application:
    name: product
    # \u6682\u4E14\u4E0D\u4F7F\u7528druid\u7B49\u6570\u636E\u5E93\u8FDE\u63A5\u6C60\uFF0C\u4E5F\u6682\u4E14\u4E0D\u7528\u914D\u7F6E\u591A\u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root@pxf
    url: jdbc:mysql://localhost:3306/c-cloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    jpa:
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
