server:
  port: 8888

spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root@pxf
    url: jdbc:mysql://localhost:3306/c-cloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    jpa:
      show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
