server:
  port: 1234
spring:
  application:
    name: gateway
  redis:
    host: 127.0.0.1
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  sensitive-headers:
#  routes:
#    myProduct:
#      path: /myProduct/**
#      serviceId: product
#      sensitiveHeaders:                  #设置为空，过滤掉cookie拦截
#  ignored-patterns:
#    - /**/product/listForOrder
#    - /product/product/listForOrder

logging:
  level:
    web: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"    #这里开启actuator 暴露端点，可以通过 /routes  访问所有的微服务代理路由

